name: ui_design
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dart_jts: ^0.3.0+1
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  toggle_switch: ^2.1.0
  timer_builder: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
